# Make target to specify building the moto_mm.ko from within Android build system.
LOCAL_PATH := $(call my-dir)
# Path to DLKM make scripts
DLKM_DIR := $(TOP)/device/qcom/common/dlkm

include $(CLEAR_VARS)
KERNEL_CFLAGS += CONFIG_HYBRIDSWAP_ZRAM=y
KERNEL_CFLAGS += CONFIG_HYBRIDSWAP=y
KERNEL_CFLAGS += CONFIG_HYBRIDSWAP_SWAPD=y
KERNEL_CFLAGS += CONFIG_HYBRIDSWAP_CORE=y

KBUILD_OPTIONS += CONFIG_HYBRIDSWAP_ZRAM=y
KBUILD_OPTIONS += CONFIG_HYBRIDSWAP=y
KBUILD_OPTIONS += CONFIG_HYBRIDSWAP_SWAPD=y
KBUILD_OPTIONS += CONFIG_HYBRIDSWAP_CORE=y

LOCAL_MODULE := moto_swap.ko
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_PATH := $(KERNEL_MODULES_OUT)
KBUILD_OPTIONS_GKI += GKI_OBJ_MODULE_DIR=gki

-include $(DLKM_DIR)/AndroidKernelModule.mk

